### PR TITLE
Fix output.bov in mpi miniapp solution

### PR DESCRIPTION
**Pull request by rjanalik**
Remove "," in output.bov
The same problem is very likely also in openmp solution

### CODE REVIEW

**Comment by vkarak** [comment]
I have fixed it in all of the rest. It's only on the MPI code that I hadn't access.

**Comment by rjanalik** [comment]
I think openmp solution has the same problem. Only cxx. But I didn't test that. I only looked at the source code.

**Comment by vkarak** [comment]
I remember fixing the code given to the students, but it could have slipped my attention that on the solutions. You can go ahead and fix this as well.

I know it's only on C++ code, since the problem arose when I moved the plotting script outside each directory and then I realised that the `bov` file was generated differently between C++ and Fortran. Since it was easier for me to fix the C++ code, I kept the Fortran versions intact.

**Comment by rjanalik** [comment]
I am talking about the openmp solution. The code we gave to the students is OK.
I'll fix it and create another pull request in a few minutes.

**Pull request merged**
